export const TOOL_FRAME_CIRCLE = 'circle'
export const TOOL_FRAME_PARTICLES_RECT = 'particlesRect'
export const TOOL_FRAME_PARTICLES_CIRCLE = 'particlesCircle'
export const TOOL_FRAME_SPRAY_CIRCLE = 'sprayCircle'
export const TOOL_FRAME_IMAGE = 'image'
